# Generated by Django 5.0.1 on 2026-01-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountdetail_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='platform',
            field=models.CharField(max_length=50),
        ),
    ]
