# Generated by Django 5.0.1 on 2026-01-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountdetail_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='nick',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='platform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='withdraw_pass',
            field=models.CharField(blank=True, help_text='Withdrawal password'),
        ),
    ]
