# Generated by Django 5.0.1 on 2026-01-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountdetail_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='brain_api',
            field=models.CharField(blank=True),
        ),
    ]
