# Generated by Django 5.0.1 on 2026-02-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_platform_alter_accountdetail_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetail',
            old_name='brain_api',
            new_name='api',
        ),
    ]
