# Generated by Django 5.0.1 on 2026-02-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_brain_api_accountdetail_api'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accountdetail',
            constraint=models.UniqueConstraint(fields=('nick', 'platform'), name='unique_nick_platform'),
        ),
        migrations.AddConstraint(
            model_name='accountdetail',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('email', 'platform'), name='unique_email_platform'),
        ),
        migrations.AddConstraint(
            model_name='accountdetail',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False), ('phone__gt', '')), fields=('phone', 'platform'), name='unique_phone_platform'),
        ),
    ]
