# Generated by Django 5.0.1 on 2026-02-11 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountdetail_unique_nick_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playsession',
            name='end_time',
            field=models.TimeField(default=datetime.time(13, 0)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='playsession',
            unique_together={('account', 'session_date', 'start_time')},
        ),
        migrations.AlterModelOptions(
            name='playsession',
            options={'ordering': ['-session_date', '-start_time'], 'verbose_name': 'Play Session', 'verbose_name_plural': 'Play Sessions'},
        ),
        migrations.RemoveField(
            model_name='playsession',
            name='is_active',
        ),
    ]
