# Generated by Django 5.0.1 on 2026-02-13 14:21

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_playsession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_days_per_year', models.FloatField()),
                ('play_days_per_week', models.FloatField()),
                ('hours_played_per_day', models.FloatField()),
                ('schedul_of_the_week', models.JSONField(default=accounts.models.default_schedule)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='play_info', to='accounts.accountdetail')),
            ],
        ),
    ]
