# Generated by Django 5.0.1 on 2026-02-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_playinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='device_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
