# Generated by Django 5.0.1 on 2026-02-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_accountdetail_device_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='device_name',
        ),
    ]
