# Generated by Django 5.0.1 on 2026-02-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_accountdetail_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='device_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
