# Generated by Django 5.0.1 on 2026-02-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_network_proxyvpn_walletprovider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasttransaction',
            name='picture',
            field=models.ImageField(blank=True, upload_to='transactions/'),
        ),
    ]
