# Generated by Django 5.0.1 on 2026-02-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_lasttransaction_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasttransaction',
            name='first_withdraw',
            field=models.BooleanField(default=False),
        ),
    ]
