# Generated by Django 5.0.1 on 2026-02-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_lasttransaction_first_withdraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playinfo',
            old_name='schedul_of_the_week',
            new_name='schedule_of_the_week',
        ),
    ]
