# Generated by Django 5.0.1 on 2026-02-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_schedul_of_the_week_playinfo_schedule_of_the_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playinfo',
            name='hours_played_per_day',
        ),
        migrations.AddField(
            model_name='playsession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
