# Generated by Django 5.0.1 on 2026-02-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_playinfo_hours_played_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playsession',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
