# Generated by Django 5.0.1 on 2026-02-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_playsession_pause_time_playsession_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='playinfo',
            name='hours_per_day',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
