# Generated by Django 5.0.1 on 2026-02-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_playinfo_hours_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playinfo',
            name='hours_per_day',
            field=models.FloatField(blank=True),
        ),
    ]
