# Generated by Django 5.0.1 on 2026-02-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_depositwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
