# Generated by Django 5.0.1 on 2026-02-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_playsession_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
