# Generated by Django 5.0.1 on 2026-02-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_playsession_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
