# Generated by Django 5.0.1 on 2026-02-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_accountdetail_is_active_accountdetail_is_banned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
