# Generated by Django 5.0.1 on 2026-02-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_accountdetail_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='break_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
