# Generated by Django 5.0.1 on 2026-02-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_accountdetail_is_active'),
        ('accounts', '0028_playsession_break_until_and_more'),
    ]

    operations = [
    ]
