# Generated by Django 5.0.1 on 2026-02-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_merge_20260223_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.network'),
        ),
    ]
