# Generated by Django 5.0.1 on 2026-02-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_deposit_withdrawal_delete_depositwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='wallet_name',
            field=models.CharField(blank=True, default=''),
        ),
    ]
