# Generated by Django 5.0.1 on 2026-02-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_deposit_status_withdrawal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_name',
            field=models.CharField(blank=True, default=''),
        ),
    ]
