# Generated by Django 5.0.1 on 2026-02-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_withdrawal_wallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
