# Generated by Django 5.0.1 on 2026-02-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_smsplatform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsplatform',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='smsplatform',
            name='country',
        ),
        migrations.AddField(
            model_name='countryblacklist',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='countries', to='accounts.smsplatform'),
        ),
        migrations.AlterField(
            model_name='smsplatform',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
