# Generated by Django 5.0.1 on 2026-02-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_smsplatform_options_remove_smsplatform_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsplatform',
            name='name',
            field=models.CharField(),
        ),
    ]
