# Generated by Django 5.0.1 on 2026-02-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_smsplatform_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('detail', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'task_log',
                'ordering': ['-ran_at'],
            },
        ),
    ]
