# Generated by Django 5.0.1 on 2026-02-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_tasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='is_active_no_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
