# Generated by Django 5.0.1 on 2026-03-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_devicecommand_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playinfo',
            name='session_durations',
            field=models.JSONField(blank=True, default=list, help_text='List of session durations in minutes, e.g. [30, 45, 60, 90]'),
        ),
        migrations.AddField(
            model_name='playsession',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
