# Generated by Django 5.0.1 on 2026-03-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_playinfo_session_durations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playsession',
            name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='playinfo',
            name='session_durations',
            field=models.JSONField(blank=True, default=list, help_text='Actual session durations played today (in minutes). Resets daily.'),
        ),
    ]
