# Generated by Django 5.0.1 on 2026-03-20 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='related_to',
            field=models.ForeignKey(blank=True, help_text='Main account this account is related to (max 2 related per main account)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_accounts', to='accounts.accountdetail'),
        ),
    ]
